name         'adobe_em6'
version      'RELEASE_1.5.1'
summary      'Install and configure Adobe AEM 6.x'
description  'Install and configure Adobe AEM 6.x'
author       'twcable'
project_page 'https://github.com/twcable/puppet-adobe_em6'

dependency 'puppetlabs/stdlib', '>=4.2.0'
dependency 'puppetlabs/java', '>=1.2.0'
dependency 'nanliu/puppet-staging', '>=1.0.2'
dependency 'maestrodev/puppet-wget', '>=1.5.7'
